[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = ".env"
auto_detect_solc = true
size_limit = 0

# [profile.default.optimizer]
# enabled = true
# runs = 200

optimizer = true
optimizer_runs = 200
# via_ir = true
